### ISSUE TITLE
Callbacks with AniSequence

### ISSUE THREAD

**Issue by lapico** [b-g/Ani#17]
It would be very useful to have callbacks within sequences.

`seq.setCallback("myFunction");`

This would allow to inject logic inside animations.

Maybe it's already possible but I didn't catch it ?

Thanks for the library 👍

**Comment by b-g** [comment]
Thanks! I'm afraid but this is not planned ... 

However a workaround which should do the trick, is to add a callback to an animation of the sequence. Check e.g.: 

https://github.com/b-g/Ani/blob/master/examples/Ani_Sequence_Loop/Ani_Sequence_Loop.pde#L48

Hope that helps! Best, Benedikt
