### ISSUE TITLE
Documentation + Processing 4 Contribution Manager inclusion

### ISSUE THREAD

**Issue by rapatski** [b-g/Ani#20]
Hello Benedikt!

Loving the look of this library, but having trouble getting it to run, with most links being dead; links from the Processing libaries webpage 404, and same for the online Documentation. The Contribution Manager doesn't list Ani any more and  when I download the zip from here, it seems to be missing the compiled library jars?

Thanks!

**Comment by b-g** [comment]
Hello @rapatski, many thanks for the interest! I've updated the README.md with a working link and a hint that "This repository is no longer maintained". Best of luck with Ani! Best, Benedikt

https://github.com/b-g/Ani/blob/master/README.md
